INSERT INTO USERS (user_id, first_name, last_name, year_of_birth, month_of_birth, day_of_birth, gender)
SELECT DISTINCT USER_ID, FIRST_NAME, LAST_NAME, YEAR_OF_BIRTH, MONTH_OF_BIRTH, DAY_OF_BIRTH, GENDER 
FROM project1.PUBLIC_USER_INFORMATION;

INSERT INTO FRIENDS (user1_id, user2_id)
SELECT DISTINCT USER1_ID, USER2_ID
FROM project1.PUBLIC_ARE_FRIENDS;

INSERT INTO PROGRAMS (institution, concentration, degree)
SELECT DISTINCT INSTITUTION_NAME, PROGRAM_CONCENTRATION, PROGRAM_DEGREE FROM project1.PUBLIC_USER_INFORMATION
WHERE INSTITUTION_NAME IS NOT NULL
AND PROGRAM_CONCENTRATION IS NOT NULL
AND PROGRAM_DEGREE IS NOT NULL;

INSERT INTO EDUCATION (user_id, program_id, program_year)
SELECT DISTINCT USERS.user_id, PROGRAMS.program_id, DATA.PROGRAM_YEAR FROM USERS, PROGRAMS, project1.PUBLIC_USER_INFORMATION DATA
WHERE USERS.user_id = DATA.USER_ID
AND PROGRAMS.institution = DATA.INSTITUTION_NAME
AND PROGRAMS.concentration = DATA.PROGRAM_CONCENTRATION
AND PROGRAMS.degree = DATA.PROGRAM_DEGREE;

INSERT INTO CITIES (city_name, state_name, country_name)
SELECT DISTINCT HOMETOWN_CITY, HOMETOWN_STATE, HOMETOWN_COUNTRY 
FROM project1.PUBLIC_USER_INFORMATION 
UNION
SELECT DISTINCT CURRENT_CITY, CURRENT_STATE, CURRENT_COUNTRY 
FROM project1.PUBLIC_USER_INFORMATION
UNION
SELECT DISTINCT EVENT_CITY, EVENT_STATE, EVENT_COUNTRY 
FROM project1.PUBLIC_EVENT_INFORMATION;

INSERT INTO USER_HOMETOWN_CITIES (user_id, hometown_city_id)
SELECT DISTINCT USERS.user_id, CITIES.city_id FROM USERS, CITIES, project1.PUBLIC_USER_INFORMATION DATA
WHERE USERS.user_id = DATA.USER_ID
AND CITIES.city_name = DATA.HOMETOWN_CITY
AND CITIES.state_name = DATA.HOMETOWN_STATE
AND CITIES.country_name = DATA.HOMETOWN_COUNTRY;

INSERT INTO USER_CURRENT_CITIES (user_id, current_city_id)
SELECT DISTINCT USERS.user_id, CITIES.city_id FROM USERS, CITIES, project1.PUBLIC_USER_INFORMATION DATA
WHERE USERS.user_id = DATA.USER_ID
AND CITIES.city_name = DATA.CURRENT_CITY
AND CITIES.state_name = DATA.CURRENT_STATE
AND CITIES.country_name = DATA.CURRENT_COUNTRY;

INSERT INTO USER_EVENTS (event_id, event_creator_id, event_name, event_tagline, event_description, event_host, event_type, event_subtype, event_address, event_city_id, event_start_time, event_end_time) 
SELECT DISTINCT EVENT_ID, EVENT_CREATOR_ID, EVENT_NAME, EVENT_TAGLINE, EVENT_DESCRIPTION, EVENT_HOST, EVENT_TYPE, EVENT_SUBTYPE, EVENT_ADDRESS, CITIES.city_id, EVENT_START_TIME, EVENT_END_TIME 
FROM project1.PUBLIC_EVENT_INFORMATION EVENTS 
LEFT JOIN CITIES ON EVENTS.EVENT_CITY = CITIES.city_name
LEFT JOIN CITIES ON EVENTS.EVENT_STATE = CITIES.state_name
LEFT JOIN CITIES ON EVENTS.EVENT_COUNTRY = CITIES.country_name;

SET AUTOCOMMIT OFF

INSERT INTO ALBUMS (album_id, album_owner_id, album_name, album_created_time, album_modified_time, album_link, album_visibility, cover_photo_id)
SELECT DISTINCT ALBUM_ID, OWNER_ID, ALBUM_NAME, ALBUM_CREATED_TIME, ALBUM_MODIFIED_TIME, ALBUM_LINK, ALBUM_VISIBILITY, COVER_PHOTO_ID 
FROM project1.PUBLIC_PHOTO_INFORMATION;

INSERT INTO PHOTOS (photo_id, album_id, photo_caption, photo_created_time, photo_modified_time, photo_link)
SELECT DISTINCT PHOTO_ID, ALBUM_ID, PHOTO_CAPTION, PHOTO_CREATED_TIME, PHOTO_MODIFIED_TIME, PHOTO_LINK 
FROM project1.PUBLIC_PHOTO_INFORMATION; 
COMMIT

SET AUTOCOMMIT ON

INSERT INTO TAGS (tag_photo_id, tag_subject_id, tag_created_time, tag_x, tag_y)
SELECT DISTINCT PHOTO_ID, TAG_SUBJECT_ID, TAG_CREATED_TIME, TAG_X_COORDINATE, TAG_Y_COORDINATE
FROM project1.PUBLIC_TAG_INFORMATION;